
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = " \x17\x16\xd6\xbb\xaa'\xa5&\x0cb*\xf9\xaf\xb1\xfb"
    
_lr_action_items = {'NUM':([3,],[4,]),'PyC':([4,],[5,]),'ID':([0,],[2,]),'IG':([2,],[3,]),'$end':([1,5,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> ID IG NUM PyC','S',4,'p_asign','miniC.py',43),
]
